#!/bin/sh

# this regex is fine for most cases
# https://www.crossref.org/blog/dois-and-matching-regular-expressions/
# no need for "sort" before "uniq", as references are unlikely to be inside the text
# also since only A-Z is mentioned and not a-z (which might still happen), convert to upper case
grep -ioP "10.\d{4,9}/[-._;()/:A-Z0-9]+" - | tr '[:lower:]' '[:upper:]' | uniq
