#!/bin/sh

# Infer DOI from a PDF file based on its metadata
# The GPLv3 License (GPLv3)
#
# Copyright (c) 2024 Ivan Boikov
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


if [ -z "$1" ] && [ -t 0 ]; then
	printf "Usage: doi-infer [PDF]...\n\nNoninteractively infer DOI of PDF(-s) based on (in order)\n\t1. standard and custom metadata\n\t2. document-level metadata\n\t3. PDF content\nWith no PDF, read standard input separated by newline.\nWarning: content search returns everything found and can be incorrect (example: DOI of a reference).\n"
	exit
fi

process_file(){
	if [ ! -f "$1" ]; then printf "File %s not found\n" "$1" && shift && return; fi

	# "custom" = standard+custom properties
	# "meta" = document-level metadata
	# both are likely to be correct
	doi="$(pdfinfo -custom "$1" | doi-grep)" || doi="$(pdfinfo -meta "$1" | doi-grep)"

	if [ -z "$doi" ]; then
		doi="$(pdftotext -q "$1" - | doi-grep)"
		[ -n "$doi" ] && >&2 echo "Warning: DOI found in content only, mistakes are likely"
	fi

	echo "$doi"
}

[ ! -t 0 ] && while read -r file || [ -n "$file" ]; do
	process_file "$file"
done

while [ "$#" -ne 0 ]; do
	process_file "$1"
	shift
done
