#!/bin/sh

# Infer DOI from a PDF file based on its metadata
# The GPLv3 License (GPLv3)
#
# Copyright (c) 2024 Ivan Boikov
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


[ -z "$1" ] && printf "Usage: doi-infer [PDF]\n\nNoninteractively infer DOI of a PDF based on (in order)\n\t1. standard and custom metadata\n\t2. document-level metadata\n\t3. PDF content\nWarning: content search returns everything found and can be incorrect (example: DOI of a reference).\n" && exit

grep_doi(){
	# this regex is fine for most cases
	# https://www.crossref.org/blog/dois-and-matching-regular-expressions/
	# no need for "sort" before "uniq", as references are unlikely to be inside the text
	# also since only A-Z is mentioned and not a-z (which might still happen), convert to upper case
	grep -ioP "10.\d{4,9}/[-._;()/:A-Z0-9]+" - | tr '[:lower:]' '[:upper:]' | uniq
}

# "custom" = standard+custom properties
# "meta" = document-level metadata
# both are likely to be correct
doi="$(pdfinfo -custom "$1" | grep_doi)" || doi="$(pdfinfo -meta "$1" | grep_doi)"

if [ -z "$doi" ]; then
	doi="$(pdftotext -q "$1" - | grep_doi)"
	if [ -n "$doi" ]; then
		>&2 echo "Warning: DOI found in content only, mistakes are likely"
	fi
fi

echo "$doi"
