#!/bin/sh

# Query CrossRef for a BibTeX entry from a DOI
# The GPLv3 License (GPLv3)
#
# Copyright (c) 2024 Ivan Boikov
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


if [ -z "$1" ] && [ -t 0 ]; then
	echo "Usage: doi-to-bibtex [DOI]...\n\nFetch Bibtex entry from Crossref based on given DOI.\nWith no DOI, read standard input separated by newline." && exit
fi

query(){
	# xargs trims excess spaces
	cached-curl "http://api.crossref.org/works/$1/transform/application/x-bibtex" | xargs
}

[ ! -t 0 ] && while read -r line || [ -n "$line" ]; do
	query "$line"
done

while [ "$#" -ne 0 ]; do
	query "$1"
	shift
done
